apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: codesealer-cni
  labels:
    {{- include "codesealer-cni.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: codesealer-cni
subjects:
- kind: ServiceAccount
  name: codesealer-cni
  namespace: {{ .Release.Namespace }}
---
{{- if .Values.cni.repair.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: codesealer-cni-repair-rolebinding
  labels:
    k8s-app: codesealer-cni-repair
    {{- include "codesealer-cni.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: codesealer-cni
  namespace: {{ .Release.Namespace}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: codesealer-cni-repair-role
{{- end }}
---