apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: codesealer-cni
  labels:
    app: codesealer-cni
    release: {{ .Release.Name }}
    codesealer.com/rev: {{ .Values.revision | default "default" }}
    install.operator.codesealer.com/owning-resource: {{ .Values.ownerName | default "unknown" }}
    operator.codesealer.com/component: "Cni"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: codesealer-cni
subjects:
- kind: ServiceAccount
  name: codesealer-cni
  namespace: {{ .Release.Namespace }}
---
{{- if .Values.cni.repair.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: codesealer-cni-repair-rolebinding
  labels:
    k8s-app: codesealer-cni-repair
    codesealer.com/rev: {{ .Values.revision | default "default" }}
    install.operator.codesealer.com/owning-resource: {{ .Values.ownerName | default "unknown" }}
    operator.codesealer.com/component: "Cni"
subjects:
- kind: ServiceAccount
  name: codesealer-cni
  namespace: {{ .Release.Namespace}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: codesealer-cni-repair-role
{{- end }}
---
{{- if .Values.cni.ambient.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: codesealer-cni-ambient
  labels:
    k8s-app: codesealer-cni-repair
    codesealer.com/rev: {{ .Values.revision | default "default" }}
    install.operator.codesealer.com/owning-resource: {{ .Values.ownerName | default "unknown" }}
    operator.codesealer.com/component: "Cni"
subjects:
  - kind: ServiceAccount
    name: codesealer-cni
    namespace: {{ .Release.Namespace}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: codesealer-cni-ambient
{{- end }}