apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: codesealer-cni
  labels:
    app: codesealer-cni
    release: {{ .Release.Name }}
    codesealer.com/rev: {{ .Values.revision | default "default" }}
    install.operator.codesealer.com/owning-resource: {{ .Values.ownerName | default "unknown" }}
    operator.codesealer.com/component: "Cni"
rules:
- apiGroups: [""]
  resources: ["pods","nodes","namespaces"]
  verbs: ["get", "list", "watch"]
---
{{- if .Values.cni.repair.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: codesealer-cni-repair-role
  labels:
    app: codesealer-cni
    release: {{ .Release.Name }}
    codesealer.com/rev: {{ .Values.revision | default "default" }}
    install.operator.codesealer.com/owning-resource: {{ .Values.ownerName | default "unknown" }}
    operator.codesealer.com/component: "Cni"
rules:
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["watch", "get", "list"]
{{- if .Values.cni.repair.repairPods }}
{{- /*  No privileges needed*/}}
{{- else if .Values.cni.repair.deletePods }}
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["delete"]
{{- else if .Values.cni.repair.labelPods }}
  - apiGroups: [""]
    {{- /* pods/status is less privileged than the full pod, and either can label. So use the lower pods/status */}}
    resources: ["pods/status"]
    verbs: ["patch", "update"]
{{- end }}
{{- end }}
---
{{- if .Values.cni.ambient.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: codesealer-cni-ambient
  labels:
    app: codesealer-cni
    release: {{ .Release.Name }}
    codesealer.com/rev: {{ .Values.revision | default "default" }}
    install.operator.codesealer.com/owning-resource: {{ .Values.ownerName | default "unknown" }}
    operator.codesealer.com/component: "Cni"
rules:
- apiGroups: [""]
  {{- /* pods/status is less privileged than the full pod, and either can label. So use the lower pods/status */}}
  resources: ["pods/status"]
  verbs: ["patch", "update"]
{{- end }}