{{- $defaultBinDir :=
    (.Capabilities.KubeVersion.GitVersion | contains "-gke") | ternary
      "/home/kubernetes/bin"
      "/opt/cni/bin"
}}
kind: ConfigMap
apiVersion: v1
metadata:
  name: codesealer-cni-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "codesealer-cni.labels" . | nindent 4 }}
data:
  # The CNI network configuration to add to the plugin chain on each node.  The special
  # values in this config will be automatically populated.
  cni_network_config: |-
        {
          "cniVersion": "0.3.1",
          "name": "codesealer-cni",
          "type": "codesealer-cni",
          "log_level": {{ quote .Values.cni.logLevel }},
          "log_uds_address": "__LOG_UDS_ADDRESS__",
          "kubernetes": {
              "kubeconfig": "__KUBECONFIG_FILEPATH__",
              "cni_bin_dir": {{ .Values.cni.cniBinDir | default $defaultBinDir | quote }},
              "exclude_namespaces": [ {{ range $idx, $ns := .Values.cni.excludeNamespaces }}{{ if $idx }}, {{ end }}{{ quote $ns }}{{ end }} ]
          }
        }